project_id = "tibyzcduahvsdybpjwuu"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chat-professor]
    verify_jwt = false
  [functions.check-registration]
    verify_jwt = false
  [functions.process-pdf]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
